Repository apcountryman/prototype-kicad-project-ci-cd, pull requests merged in 2021-09, with the labels that each got.

#10 Add design rules compliance CI job
  .github/workflows/ci.yml
  ci/check-design-rules-compliance
Labels: priority-normal, status-in_review, type-feature

#12 Remove unused function
  ci/check-electrical-rules-compliance
Labels: priority-normal, status-in_review, type-refactoring

#14 Add Jay Lamb to authors list
  README.md
Labels: priority-normal, status-in_review, type-enhancement

#16 Add schematic PDF(s) generation CI job
  .github/workflows/ci.yml
  ci/generate-schematic-pdfs
Labels: priority-normal, status-in_review, type-feature

#18 Fix CI scripts description indentation
  ci/check-design-rules-compliance
  ci/check-electrical-rules-compliance
Labels: priority-normal, status-in_review, type-bug
